### ISSUE TITLE
Diseño pagina web GUI

### ISSUE THREAD

**Issue by John-Castaneda** [John-Castaneda/ACME#11]

**Comment by Marc0Acm3** [comment]
![Proyecto Módulo Programación Web G_pages-to-jpg-0001](https://user-images.githubusercontent.com/87943493/140852364-6aebaf9a-c4b4-4e07-8977-997129301c64.jpg)
![Proyecto Módulo Programación Web G_pages-to-jpg-0002](https://user-images.githubusercontent.com/87943493/140852365-14407f7e-b666-4f46-9bbe-8c3145cde8d2.jpg)
![Proyecto Módulo Programación Web G_pages-to-jpg-0003](https://user-images.githubusercontent.com/87943493/140852366-921b200b-14ec-4e21-badb-d6d065b1e464.jpg)
![Proyecto Módulo Programación Web G_pages-to-jpg-0004](https://user-images.githubusercontent.com/87943493/140852369-41ddd192-16f6-40f6-ab66-a639d49110fc.jpg)
![Proyecto Módulo Programación Web G_pages-to-jpg-0005](https://user-images.githubusercontent.com/87943493/140852372-62e1454b-da5a-4e57-b629-b2346eba3d83.jpg)
![Proyecto Módulo Programación Web G_pages-to-jpg-0006](https://user-images.githubusercontent.com/87943493/140852374-9613d9d9-b6c4-4fef-a75a-e273711b2957.jpg)
![Proyecto Módulo Programación Web G_pages-to-jpg-0007](https://user-images.githubusercontent.com/87943493/140852376-80814f36-2d3b-48cf-b98e-678d0c89f8ac.jpg)
![Proyecto Módulo Programación Web G_pages-to-jpg-0008](https://user-images.githubusercontent.com/87943493/140852377-83793662-6448-449e-af73-4f05f964a68c.jpg)
![Proyecto Módulo Programación Web G_pages-to-jpg-0009](https://user-images.githubusercontent.com/87943493/140852380-3bd95d58-3abf-44a5-8f4b-bc26d9313409.jpg)
![Proyecto Módulo Programación Web G_pages-to-jpg-0011](https://user-images.githubusercontent.com/87943493/140852383-5eabf3df-a506-4c0a-8f3f-f36f6e6f6768.jpg)
![Proyecto Módulo Programación Web G_pages-to-jpg-0012](https://user-images.githubusercontent.com/87943493/140852384-4ed87e9b-53e6-499a-9e9e-4f1d3fb8f466.jpg)
![Proyecto Módulo Programación Web G_pages-to-jpg-0013](https://user-images.githubusercontent.com/87943493/140852386-3a99fb53-8c0c-45cc-bc21-0f3d8a74a1da.jpg)
![Proyecto Módulo Programación Web G_pages-to-jpg-0014](https://user-images.githubusercontent.com/87943493/140852387-43d2d37b-f134-4911-ab2c-edeb708aea5e.jpg)
![Proyecto Módulo Programación Web G_pages-to-jpg-0015](https://user-images.githubusercontent.com/87943493/140852390-3f033003-ddd8-46de-b201-179b25419679.jpg)
