### ISSUE TITLE
Front end contactenos

### ISSUE THREAD

**Issue by John-Castaneda** [John-Castaneda/ACME#21]

**Comment by paty789** [comment]
![image](https://user-images.githubusercontent.com/70667468/144959386-dc60cfe2-cbbf-4b03-892f-cfd02f82f088.png)

**Comment by paty789** [comment]
![image](https://user-images.githubusercontent.com/70667468/144961004-a7a20df4-659a-4491-bb3a-3eef79e9d556.png)
