### ISSUE TITLE
Front end home

### ISSUE THREAD

**Issue by John-Castaneda** [John-Castaneda/ACME#23]

**Comment by Marc0Acm3** [comment]
ARCHIVO ZIP

[HTML.zip](https://github.com/John-Castaneda/ACME/files/7630409/HTML.zip)

IMAGEN PREVIA

![FireShot Capture 017 - SMART VEHICLE - localhost](https://user-images.githubusercontent.com/87943493/144164162-98f504cd-5bff-4f10-a275-8fae8bcd008b.png)
