### ISSUE TITLE
Front end Solicitudes

### ISSUE THREAD

**Issue by John-Castaneda** [John-Castaneda/ACME#24]

**Comment by paty789** [comment]
![image](https://user-images.githubusercontent.com/70667468/144961384-2d8b8ee2-4dac-42b9-adbe-9d4a0296c29e.png)
![image](https://user-images.githubusercontent.com/70667468/144961448-19005324-372e-49e4-92ea-2233c77d1d29.png)
![image](https://user-images.githubusercontent.com/70667468/144961485-a7966fd2-ca69-4ee8-a88e-25b8757a3e2e.png)
