### ISSUE TITLE
Crear logo del grupo

### ISSUE THREAD

**Issue by John-Castaneda** [John-Castaneda/ACME#4]

**Comment by Jetta1004** [comment]
![acme](https://user-images.githubusercontent.com/88415891/139983109-43e6a4ed-bf48-4a13-8079-8ee5f1951c24.jpg)

**Comment by AndresManjarres** [comment]
![ACMEPANDRES](https://user-images.githubusercontent.com/89228795/139984730-cc0d022d-e0d0-492c-a5cf-343fa71633f8.png)

**Comment by paty789** [comment]
![logo](https://user-images.githubusercontent.com/70667468/139989675-70313fd4-084f-4b68-b73e-46f4669f9109.JPG)

**Comment by Marc0Acm3** [comment]
![Acme](https://user-images.githubusercontent.com/87943493/140594720-c72203e7-44bb-4c02-b0bb-7e70eb6781b5.jpg)
