### ISSUE TITLE
Definición Proyecto final

### ISSUE THREAD

**Issue by John-Castaneda** [John-Castaneda/ACME#6]

**Comment by Jetta1004** [comment]
[Proyecto Desarrollo de aplicaciones Web Ciclo 4a G1 SMART VEHICLE.pdf](https://github.com/John-Castaneda/ACME/files/7501047/Proyecto.Desarrollo.de.aplicaciones.Web.Ciclo.4a.G1.SMART.VEHICLE.pdf)

**Comment by Jetta1004** [comment]
Entregan el  proyecto final
