### ISSUE TITLE
Diagramas no relacional

### ISSUE THREAD

**Issue by John-Castaneda** [John-Castaneda/ACME#7]
Crear Diagrama Clase del proyecto

**Comment by John-Castaneda** [comment]
[arquitectura proyecto ciclo04.zip](https://github.com/John-Castaneda/ACME/files/7501212/arquitectura.proyecto.ciclo04.zip)

**Comment by Jetta1004** [comment]
![acme logo](https://user-images.githubusercontent.com/88415891/140854854-54f3eff5-f24e-4ead-aa78-1665672098bc.jpg)

**Comment by Jetta1004** [comment]
[SMART VEHICLE DIAGRAMA NO SQL.drawio.pdf](https://github.com/John-Castaneda/ACME/files/7501596/SMART.VEHICLE.DIAGRAMA.NO.SQL.drawio.pdf)

**Comment by Jetta1004** [comment]
![SMART VEHICLE DIAGRAMA NO SQL](https://user-images.githubusercontent.com/88415891/140857483-b8bfd454-04c1-4d6d-a41f-caeca3ff214f.jpg)

**Comment by Jetta1004** [comment]
se le adicionaron unos detalles a vehiculo

**Comment by Jetta1004** [comment]
![SMART VEHICLE DIAGRAMA NO SQL](https://user-images.githubusercontent.com/88415891/141323487-00bd6697-4531-4430-946f-3bb85ba05019.jpg)

**Comment by Jetta1004** [comment]
![SMART VEHICLE DIAGRAMA NO SQL - copia](https://user-images.githubusercontent.com/88415891/141598728-fc68b691-032b-430a-ab84-1b958ac1405e.jpg)

**Comment by Jetta1004** [comment]
Se hace el diagrama con las relaciones

**Comment by Jetta1004** [comment]
![SMART VEHICLE DIAGRAMA NO SQL  FINAL ](https://user-images.githubusercontent.com/88415891/141798429-c89b32af-e227-42c6-9755-334c2f53793c.jpg)

**Comment by Jetta1004** [comment]
![SMART VEHICLE DIAGRAMA NO SQL FINAL2](https://user-images.githubusercontent.com/88415891/141828226-a64b755b-660d-42dd-a656-0b557689e6e4.jpg)

**Comment by Jetta1004** [comment]
![SMART VEHICLE DIAGRAMA NO SQL FINAL 3](https://user-images.githubusercontent.com/88415891/141887361-66f927fd-4332-4fa1-b3d6-fc5ddb3da910.jpg)

**Comment by Jetta1004** [comment]
![SMART VEHICLE DIAGRAMA NO SQL FINAL 18-11-2021](https://user-images.githubusercontent.com/88415891/142565610-3afa677c-0f9d-4d6d-a933-8e7dfa5baa35.jpg)

**Comment by Jetta1004** [comment]
SE ACTUALIZA MODELOS
